index:
    path: /
    controller: App\Controller\DefaultController::index
    
app_login:
    path: /security/login
    controller:  App\Controller\SecurityController::login
    
app_logout:
    path: /security/logout
    methods: GET
    #controller: App\Controller\SecurityController::logout

app_registration:
    path: /registration
    controller:  App\Controller\RegistrationController::Registration
app_regvalid:
    path: /regvalid
    controller:  App\Controller\RegistrationController::valid

app_cabinet:
    path: /cabinet
    controller:  App\Controller\UserController::cabinet

app_goods:
    path: /cabinet/addgoods
    controller:  App\Controller\UserController::addgoods

app_mygoods:
    path: /cabinet/mygoods
    controller:  App\Controller\UserController::mygoods

app_reggoods:
    path: /cabinet/addgoods/check
    controller:  App\Controller\UserController::reggoods

app_showgoods:
    path: /cabinet/showgoods
    controller:  App\Controller\UserController::ShowGoods

